Fetch in react - Laura Grace Manimtim
lauragracem/rc0522-code-solutions pull request #104
Opened 2022-07-20 19:27 UTC by lauragracem

<img width="964" alt="Screen Shot 2022-07-20 at 12 26 22 PM" src="https://user-images.githubusercontent.com/60913524/180065670-251a2304-8d7a-4bd1-a7d1-14747cd49419.png">

2022-07-20 23:27 UTC, scbowler requested changes
Looking good, just one update needed. Let me know if you have any questions.

2022-07-20 23:27 UTC, scbowler commented on fetch-in-react/src/app.jsx
> +        this.setState({ isLoading: false });
This should be done with a single `setState` call:
```JAVASCRIPT
this.setState({ users, isLoading: false });
```

2022-07-21 19:37 UTC, scbowler requested changes
One more update needed. Let me know if you have any questions.

2022-07-21 19:37 UTC, scbowler commented on fetch-in-react/src/app.jsx
> +        this.setState({ isLoading: false });
You need to update the `users` in state and `isLoading`. Make sure you are testing your code when you make updates.
```JAVASCRIPT
this.setState({ users: users, isLoading: false });
```

2022-07-22 22:15 UTC, TimelikeClosure approved these changes

2022-07-22 22:15 UTC, merged